services:
  - type: web
    name: beat-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bot:app"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
