services:
  - type: web
    name: beat-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: PORT
        value: 10000
    plan: free
    build:
      packages:
        - ffmpeg
