services:
  - type: web
    name: beat-analyzer-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: PORT
        value: 10000
    plan: free
