services:
  - type: web
    name: beat-analyzer-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: PORT
        value: 10000
