[build]
nixpacksPlan = "default"

[build.default]
builder = "NIXPACKS"
buildCommand = """
  apt update && apt install -y ffmpeg
  pip install --upgrade pip
  pip install -r requirements.txt
"""
startCommand = "gunicorn bot:app"
