[build]
nixpacksVersion = "1.38.0"

[build.nixpacksPlan]
phases.setup = { nixPkgs = ["ffmpeg"] }
phases.install = { cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"] }
phases.start = { cmd = "gunicorn bot:app" }
