[build]
nixpacksVersion = "1.17.0"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r requirements.txt"]

[build.nixpacksPlan.phases.start]
cmds = ["gunicorn bot:app"]
