[build]
nixpacksVersion = "1.38.0"

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["ffmpeg"]

[build.nixpacksPlan.phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[build.nixpacksPlan.phases.start]
cmds = ["gunicorn bot:app"]
