[build]
nixpacksPlan = { 
  phases = {
    setup = { nixPkgs = ["ffmpeg", "python312", "python312Packages.pip"] },
    install = "pip install -r requirements.txt",
    start = "gunicorn bot:app"
  }
}
