[build]
nixpacksPlan = { 
  setup = ["ffmpeg"], 
  install = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
  ] 
}

[start]
cmd = "gunicorn bot:app"
