[build]
nixpacksPlan = { 
  phases = {
    setup = { packages = ["ffmpeg"] },
    install = { commands = ["pip install --upgrade pip", "pip install -r requirements.txt"] },
    start = { cmd = "gunicorn bot:app" }
  }
}
