[build]
nixpacksVersion = "1.38.0"

[build.nixpacksPlan]
phases = { 
  setup = { nixPkgs = ["ffmpeg", "python312", "python312Packages.pip"] }, 
  install = { cmd = "pip install --upgrade pip && pip install -r requirements.txt" }, 
  start = { cmd = "gunicorn bot:app" } 
}
