[build]
nixpacksVersion = "1.17.0"

[deploy]
startCommand = "gunicorn bot:app"

[build.nixpacksPlan]
phases.install = { cmds = [
  "apt update && apt install -y ffmpeg",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
] }
